name: trigger workflow based on events
on: 
  pull_request:
    types:
      - created
jobs:
  test:
    runs_on: linux-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
