name: second workflow
on: workflow_dispatch
jobs:
  second_job:
    runs-on: ubuntu-latest
    steps:
      - name: greeting
        run: |
          echo "hello"
          ls -lrt
      - name: checkout
        uses: actions/checkout@v3
        with:
          brach: main
